<?php

namespace Database\Seeders;

use App\Models\Order;
use App\Models\Promotion;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Tìm hoặc tạo user với email user@meteor.com
        $targetUser = User::firstOrCreate(
            ['email' => 'user@meteor.com'],
            [
                'name' => 'User Meteor',
                'password' => bcrypt('password'),
                'role' => 'user',
                'status' => 'active',
            ]
        );

        $promotionIds = Promotion::pluck('id')->all();

        if (count($promotionIds) < 5) {
            $this->call(PromotionSeeder::class);
            $promotionIds = Promotion::pluck('id')->all();
        }

        $orders = [
            [
                'order_code' => 'MT-0001',
                'total_price' => 32900000,
                'discount_amount' => 3290000,
                'final_total' => 29610000,
                'payment_method' => 'bank',
                'payment_status' => 'paid',
                'order_status' => 'completed',
                'return_status' => 'none',
                'shipping_method' => 'GHN',
                'shipping_fee' => 150000,
                'shipping_address' => 'Số 12, Nguyễn Huệ, Quận 1',
                'shipping_city' => 'TP. Hồ Chí Minh',
                'shipping_district' => 'Quận 1',
                'shipping_ward' => 'Bến Nghé',
                'shipping_phone' => '0909000111',
                'customer_name' => 'User Meteor',
                'customer_phone' => '0909000111',
                'customer_email' => 'user@meteor.com',
                'tracking_code' => 'GHN1',
                'tracking_url' => 'https://tracking.example.com/GHN1',
                'shipping_provider' => 'GHN',
                'order_date' => Carbon::now()->subDays(15),
                'confirmed_at' => Carbon::now()->subDays(14),
                'packed_at' => Carbon::now()->subDays(13),
                'shipped_at' => Carbon::now()->subDays(12),
                'delivered_at' => Carbon::now()->subDays(10),
            ],
            [
                'order_code' => 'MT-0002',
                'total_price' => 15490000,
                'discount_amount' => 0,
                'final_total' => 15490000,
                'payment_method' => 'cash',
                'payment_status' => 'pending',
                'order_status' => 'pending',
                'return_status' => 'none',
                'shipping_method' => 'Viettel Post',
                'shipping_fee' => 90000,
                'shipping_address' => '88 Hoàng Quốc Việt, Cầu Giấy',
                'shipping_city' => 'Hà Nội',
                'shipping_district' => 'Cầu Giấy',
                'shipping_ward' => 'Nghĩa Đô',
                'shipping_phone' => '0909000222',
                'customer_name' => 'Trần Thị B',
                'customer_phone' => '0909000222',
                'customer_email' => 'user@meteor.com',
                'order_date' => Carbon::now()->subDays(7),
            ],
            [
                'order_code' => 'MT-0003',
                'total_price' => 21990000,
                'discount_amount' => 2000000,
                'final_total' => 19990000,
                'payment_method' => 'paypal',
                'payment_status' => 'paid',
                'order_status' => 'shipping',
                'return_status' => 'none',
                'shipping_method' => 'GHTK',
                'shipping_fee' => 120000,
                'shipping_address' => '25 Võ Văn Tần, Quận 3',
                'shipping_city' => 'TP. Hồ Chí Minh',
                'shipping_district' => 'Quận 3',
                'shipping_ward' => 'Võ Thị Sáu',
                'shipping_phone' => '0909000333',
                'customer_name' => 'Lê Quốc C',
                'customer_phone' => '0909000333',
                'customer_email' => 'user@meteor.com',
                'tracking_code' => 'GHTK123',
                'tracking_url' => 'https://tracking.example.com/GHTK123',
                'shipping_provider' => 'GHTK',
                'order_date' => Carbon::now()->subDays(6),
                'confirmed_at' => Carbon::now()->subDays(6),
                'packed_at' => Carbon::now()->subDays(5),
                'shipped_at' => Carbon::now()->subDays(4),
            ],
            [
                'order_code' => 'MT-0004',
                'total_price' => 8900000,
                'discount_amount' => 500000,
                'final_total' => 8400000,
                'payment_method' => 'momo',
                'payment_status' => 'paid',
                'order_status' => 'processing',
                'return_status' => 'none',
                'shipping_method' => 'Ninja Van',
                'shipping_fee' => 80000,
                'shipping_address' => '19 Lê Lợi',
                'shipping_city' => 'Đà Nẵng',
                'shipping_district' => 'Hải Châu',
                'shipping_ward' => 'Thạch Thang',
                'shipping_phone' => '0909000444',
                'customer_name' => 'Phạm Mỹ D',
                'customer_phone' => '0909000444',
                'customer_email' => 'user@meteor.com',
                'order_date' => Carbon::now()->subDays(5),
                'confirmed_at' => Carbon::now()->subDays(4),
            ],
            [
                'order_code' => 'MT-0005',
                'total_price' => 4500000,
                'discount_amount' => 0,
                'final_total' => 4500000,
                'payment_method' => 'cash',
                'payment_status' => 'failed',
                'order_status' => 'cancelled',
                'return_status' => 'none',
                'shipping_method' => 'VNPost',
                'shipping_fee' => 60000,
                'shipping_address' => '101 Trần Phú',
                'shipping_city' => 'Nha Trang',
                'shipping_district' => 'Lộc Thọ',
                'shipping_ward' => 'Lộc Thọ',
                'shipping_phone' => '0909000555',
                'customer_name' => 'Đặng Văn E',
                'customer_phone' => '0909000555',
                'customer_email' => 'user@meteor.com',
                'order_date' => Carbon::now()->subDays(4),
                'cancel_reason' => 'Khách yêu cầu hủy',
                'cancelled_at' => Carbon::now()->subDays(3),
            ],
            [
                'order_code' => 'MT-0006',
                'total_price' => 17900000,
                'discount_amount' => 790000,
                'final_total' => 17110000,
                'payment_method' => 'bank',
                'payment_status' => 'paid',
                'order_status' => 'completed',
                'return_status' => 'none',
                'shipping_method' => 'GHN',
                'shipping_fee' => 100000,
                'shipping_address' => '12 Pasteur',
                'shipping_city' => 'Huế',
                'shipping_district' => 'Phú Nhuận',
                'shipping_ward' => 'Vĩnh Ninh',
                'shipping_phone' => '0909000666',
                'customer_name' => 'Huỳnh Nhật F',
                'customer_phone' => '0909000666',
                'customer_email' => 'user@meteor.com',
                'tracking_code' => 'GHN888',
                'tracking_url' => 'https://tracking.example.com/GHN888',
                'shipping_provider' => 'GHN',
                'order_date' => Carbon::now()->subDays(9),
                'confirmed_at' => Carbon::now()->subDays(8),
                'packed_at' => Carbon::now()->subDays(7),
                'shipped_at' => Carbon::now()->subDays(6),
                'delivered_at' => Carbon::now()->subDays(4),
            ],
            [
                'order_code' => 'MT-0007',
                'total_price' => 9900000,
                'discount_amount' => 0,
                'final_total' => 9900000,
                'payment_method' => 'paypal',
                'payment_status' => 'paid',
                'order_status' => 'processing',
                'return_status' => 'none',
                'shipping_method' => 'J&T',
                'shipping_fee' => 70000,
                'shipping_address' => '55 Nguyễn Văn Linh',
                'shipping_city' => 'Cần Thơ',
                'shipping_district' => 'Ninh Kiều',
                'shipping_ward' => 'An Nghiệp',
                'shipping_phone' => '0909000777',
                'customer_name' => 'Vũ Thị G',
                'customer_phone' => '0909000777',
                'customer_email' => 'user@meteor.com',
                'order_date' => Carbon::now()->subDays(3),
                'confirmed_at' => Carbon::now()->subDays(2),
            ],
            [
                'order_code' => 'MT-0008',
                'total_price' => 5600000,
                'discount_amount' => 600000,
                'final_total' => 5000000,
                'payment_method' => 'momo',
                'payment_status' => 'paid',
                'order_status' => 'return_requested',
                'return_status' => 'requested',
                'return_reason' => 'Sản phẩm bị trầy xước',
                'shipping_method' => 'GHTK',
                'shipping_fee' => 65000,
                'shipping_address' => '102 Hùng Vương',
                'shipping_city' => 'Pleiku',
                'shipping_district' => 'Plei Ku',
                'shipping_ward' => 'Yên Đỗ',
                'shipping_phone' => '0909000888',
                'customer_name' => 'Ngô Minh H',
                'customer_phone' => '0909000888',
                'customer_email' => 'user@meteor.com',
                'order_date' => Carbon::now()->subDays(8),
                'confirmed_at' => Carbon::now()->subDays(7),
                'packed_at' => Carbon::now()->subDays(6),
                'shipped_at' => Carbon::now()->subDays(5),
                'delivered_at' => Carbon::now()->subDays(3),
                'return_note' => 'Khách gửi yêu cầu đổi trả kèm ảnh minh họa.',
            ],
            [
                'order_code' => 'MT-0009',
                'total_price' => 4300000,
                'discount_amount' => 0,
                'final_total' => 4300000,
                'payment_method' => 'cash',
                'payment_status' => 'pending',
                'order_status' => 'shipping',
                'return_status' => 'none',
                'shipping_method' => 'VNPost',
                'shipping_fee' => 50000,
                'shipping_address' => '16 Phan Chu Trinh',
                'shipping_city' => 'Quảng Nam',
                'shipping_district' => 'Tam Kỳ',
                'shipping_ward' => 'An Sơn',
                'shipping_phone' => '0909000999',
                'customer_name' => 'Phan Đình I',
                'customer_phone' => '0909000999',
                'customer_email' => 'user@meteor.com',
                'tracking_code' => 'VNPOST55',
                'tracking_url' => 'https://tracking.example.com/VNPOST55',
                'shipping_provider' => 'VNPost',
                'order_date' => Carbon::now()->subDays(2),
                'confirmed_at' => Carbon::now()->subDays(2),
                'packed_at' => Carbon::now()->subDay(),
                'shipped_at' => Carbon::now()->subHours(12),
            ],
            [
                'order_code' => 'MT-0010',
                'total_price' => 6500000,
                'discount_amount' => 500000,
                'final_total' => 6000000,
                'payment_method' => 'bank',
                'payment_status' => 'paid',
                'order_status' => 'returned',
                'return_status' => 'refunded',
                'return_reason' => 'Không đúng mẫu đặt',
                'return_note' => 'Đã xử lý hoàn tiền cho khách.',
                'refunded_at' => Carbon::now()->subDay(),
                'shipping_method' => 'GHTK',
                'shipping_fee' => 65000,
                'shipping_address' => '77 Hai Bà Trưng',
                'shipping_city' => 'Biên Hòa',
                'shipping_district' => 'Biên Hòa',
                'shipping_ward' => 'Quang Vinh',
                'shipping_phone' => '0909111100',
                'customer_name' => 'Đỗ Hữu K',
                'customer_phone' => '0909111100',
                'customer_email' => 'user@meteor.com',
                'order_date' => Carbon::now()->subDays(11),
                'confirmed_at' => Carbon::now()->subDays(10),
                'packed_at' => Carbon::now()->subDays(10),
                'shipped_at' => Carbon::now()->subDays(9),
                'delivered_at' => Carbon::now()->subDays(8),
                'cancelled_at' => null,
            ],
        ];

        foreach ($orders as $index => $data) {
            Order::updateOrCreate(
                ['order_code' => $data['order_code']],
                array_merge($data, [
                    'user_id' => $targetUser->id,
                    'promotion_id' => $promotionIds[$index % count($promotionIds)] ?? null,
                ])
            );
        }
    }
}
